name: smart_to_do
description: "Smart TODO Flutter App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.4
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  path_provider: ^2.0.8
  flutter_local_notifications: ^19.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  build_runner: any
  hive_generator: any

flutter:
  uses-material-design: true

